name: "Terraform GitHub Actions"
on:
  - push
jobs:
  format:
    name: "fmt"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "fmt"
          args: "-check -recursive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - hydra
          - ingress-nginx
          - mysql
          - postgres
          - rocket-chat
          - tls-self-signed-cert
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "init"
          tf_actions_working_dir: ${{ matrix.module }}
          args: "-backend=false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: ${{ matrix.module }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
